### PR TITLE
Publish to npm

### PR DESCRIPTION
**Pull request by JordeyWijnbergen**

### CODE REVIEW

**Comment by JordeyWijnbergen** [comment]
Created pull request for the wrong branch! Sorry for that.

**Comment by TheKeithStewart** [comment]
@JordeyWijnbergen no problem.

Looks like you are publishing a fork of this repo. Is there a reason that you don't want to contribute to the existing package instead? I'm happy to work with you to improve `angular-esri-components`.

**Comment by JordeyWijnbergen** [comment]
Hi Keith,

Only reason was I did not see any activity anymore. I tried to contact you via linked in with some questions about this. I’m fine with working together on angular-esri-components.

Kind regards,
Jordey

Verzonden vanaf mijn Windows 10-telefoon

Van: Keith Stewart<mailto:notifications@github.com>
Verzonden: dinsdag 20 februari 2018 21:51
Aan: TheKeithStewart/angular-esri-components<mailto:angular-esri-components@noreply.github.com>
CC: Jordey Wijnbergen<mailto:jordey.wijnbergen@hetconsultancyhuis.nl>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [TheKeithStewart/angular-esri-components] Publish to npm (#23)


@JordeyWijnbergen<https://github.com/jordeywijnbergen> no problem.

Looks like you are publishing a fork of this repo. Is there a reason that you don't want to contribute to the existing package instead? I'm happy to work with you to improve angular-esri-components.

**Comment by TheKeithStewart** [comment]
@JordeyWijnbergen I found where you messaged me on LinkedIn and replied to you there. Let me know if there is a different place where you'd like to discuss possible improvements to this project.

**Comment by JordeyWijnbergen** [comment]
Maybe just emailing is the best way. I will send you my email address via linked in.

**Pull request closed without merging**
